### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by sorrison** [antonlindstrom/puppet-powerdns#16]
Can you release a new version, currently can't use this from forge as 0.0.4 tag still contains hardcoded link to puppet-stdlib 3.0. master works fine so can this be tagged for a release?

**Comment by antonlindstrom** [comment]
@sorrison Thanks for pointing this out. I'll try to release a new version within a few days.

**Comment by sorrison** [comment]
Thanks

**Comment by antonlindstrom** [comment]
Sorry for the delay. The new release is up at 0.0.5 on Puppet Forge.

Thanks!

**Comment by sorrison** [comment]
OK thanks, still not working with librarian-puppet but I think it's a bug on their side
