### ISSUE TITLE
Can you add a license ?

### ISSUE THREAD

**Issue by dmsimard** [antonlindstrom/puppet-powerdns#24]
It doesn't look like the project is under any kind of license. Could you please be explicit by adding a LICENSE file and including the license header in the README ?

**Comment by dmsimard** [comment]
Just noticed https://github.com/antonlindstrom/puppet-powerdns/blob/82cf054fa43a500bd8da20151ad6843266724ad3/metadata.json#L6

**Comment by thomasgoirand** [comment]
It'd be nice to add a LICENSE file anyway, this would make it more easy to package into downstream distros. Can this happen please?

**Comment by thomasgoirand** [comment]
Hi. Thanks for this! However, could you please also fix metadata.json so that it matches version 3, and not v2? This is kind of confusing...

**Comment by antonlindstrom** [comment]
Fixed, thank you so much for reminding me of this. :+1:
